### ISSUE TITLE
If condition not cleared when all nodes are passed as N

### ISSUE THREAD

**Issue by kirtanp** [facusapienza21/optimaladj#6]
With reference, to the following line, wouldn't the condition `N == self.nodes()` always be `False`? Because `N` is passed as an array, and `self.nodes()` has the type `NodeView`.
https://github.com/facusapienza21/optimaladj/blob/d8f913391da08fe798b4443996e8567783aa9bc5/optimaladj/CausalGraph.py#L363
Here is a minimal example I thought should work but doesn't. But perhaps I'm missing something. Let me know if this makes sense and I can PR a simple fix.

```python
import numpy as np
import networkx as nx
from optimaladj.CausalGraph import CausalGraph

A = np.array(([[0., 0., 0., 1., 1., 0., 1.],
        [0., 0., 1., 1., 0., 1., 1.],
        [0., 0., 0., 1., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0.]]))
G_temp = nx.from_numpy_array(A, create_using=nx.DiGraph)

G = CausalGraph()

G.add_nodes_from(G_temp.nodes(data=True))
G.add_edges_from(G_temp.edges(data=True))

nodes = list(G.nodes)

treatment = nodes[-2]
outcome = nodes[-1]
L = []
N = nodes

G.optimal_adj_set(treatment, outcome, L, N)
```
The result is
```python
ConditionException: Conditions to guarantee the existence of an optimal adjustment set are not satisfied
```

**Comment by esmucler** [comment]
Hi Kirtan! You are right, this is a bug, thank you for raising it. If you want to submit a PR fixing it you are super welcome to.

Also, just fyi, all these methods are now a part of [DoWhy](https://github.com/py-why/dowhy/tree/main/dowhy). Luckily we did not make the same mistake in the DoWhy code. In any case, we should fix the issue in this repo.

Best

**Comment by kirtanp** [comment]
Thanks Ezequiel! I just sent a PR for the simple fix. Didn't know this was also in DoWhy now, thanks for letting me know :)
